/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thunderstone_ktv_KtvApi */

#ifndef _Included_com_thunderstone_ktv_KtvApi
#define _Included_com_thunderstone_ktv_KtvApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thunderstone_ktv_KtvApi
 * Method:    NativeCalcInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thunderstone_ktv_KtvApi_NativeCalcInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thunderstone_ktv_KtvApi
 * Method:    NativeCalcUnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thunderstone_ktv_KtvApi_NativeCalcUnInit
  (JNIEnv *, jobject);

/*
 * Class:     com_thunderstone_ktv_KtvApi
 * Method:    NativeCalcScore
 * Signature: ([BD)I
 */
JNIEXPORT jint JNICALL Java_com_thunderstone_ktv_KtvApi_NativeCalcScore
  (JNIEnv *, jobject, jbyteArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
